### ISSUE TITLE
0.6.1 Window7, when open application, there are no any content to display.

### ISSUE THREAD

**Issue by Bekrab** [junxion-io/Junxion#1]
0.6.1 Window7, when open application, there are no any content to display. Reload or Force reload doesn't help.
![image](https://user-images.githubusercontent.com/38872499/39458183-e2ec8688-4d1c-11e8-9706-5b6910846b7d.png)

**Comment by Bekrab** [comment]
Error is below
![image](https://user-images.githubusercontent.com/38872499/39585982-304785cc-4f20-11e8-81f3-b921bd9e9fb4.png)

**Comment by junxion-io** [comment]
Thank you, it appears you are on a 32-bit windows installation. We'll look into releasing a 32-bit version for the next release.

**Comment by junxion-io** [comment]
The latest release has a fix for this bug. Please let us know if you have any other troubles using the app and thanks for letting us know about the issue.

https://github.com/junxion-io/Junxion/releases/
